### ISSUE TITLE
0.19 support

### ISSUE THREAD

**Issue by ismailkarsli** [lflare/lemmy-subscriber-bot#5]
The tool is not working on 0.19 FYI

**Comment by ghost64** [comment]
It's working for me but I built a new container using the repo directly and not the latest docker hub version.  You can either build yourself or try the nightly tag on docker hub.

**Comment by lflare** [comment]
Fixed by #6

**Comment by EStork09** [comment]
@lflare would you mind either making a release for this or pushing the nightly build?

**Comment by lflare** [comment]
> @lflare would you mind either making a release for this or pushing the nightly build?

Hello, forgot to update on this, but nightly is pushed.
